### ISSUE TITLE
JSON response for missing exec simulation differs between persisting and explicitly specified

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/cordova-simulate#125] opened 2016-08-05 16:51 UTC
When testing the behavior of `cordova.exec` when there is no pre-defined plugin simulation, I saw this:

```
>cordova.exec(suc, fai, "fooService", "bar", [1])
undefined
fail
{}
>cordova.exec(suc, fai, "fooService", "bar", [1])
undefined
fail
{"0":""}
```

The first time it popped up the "Please specify a response" dialog, and I left the field empty and clicked fail, but also told it to persist the result. The first response was just `{}` as expected, an empty object, but the second time when it used the persisted result the response had a `0` property.

**Comment by dmitrii-snytkin** [comment] 2017-05-04 14:56
Can you reproduce the bug?

**Comment by drewgillies** [comment] 2017-05-16 22:01
Closing due to no repro.

**Closed by drewgillies** 2017-05-16 22:01 UTC
Labels: invalid
