### ISSUE TITLE
[Bug] Geolocation.getPermission is not being handled automatically

### ISSUE THREAD

**Issue by digeff** [Microsoft/cordova-simulate#70] opened 2016-06-09 21:28 UTC
While testing this project: https://github.com/ryanjsalva/cordova-simulate-tests/
Using the Geolocation/Locate button with 
Windows 10 with Simulate Android
cordova -v 5.4.1
cordova platforms: android 4.1.1, ios 3.9.2

cordova plugins:
cordova-plugin-add-swift-support 1.1.0 "AddSwiftSupport"
cordova-plugin-battery-status 1.1.2 "Battery"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-contacts 2.1.0 "Contacts"
cordova-plugin-dbmeter 1.0.3 "DBMeter"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-device-motion 1.2.1 "Device Motion"
cordova-plugin-device-orientation 1.0.3 "Device Orientation"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-globalization 1.0.3 "Globalization"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-media-capture 1.3.0 "Capture"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-vibration 2.1.1 "Vibration"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-sqlite-storage 1.4.1 "Cordova sqlite storage plugin"

I get an UNHANDLED EXEC CALL asking for Geolocation.getPermission.:
![image](https://cloud.githubusercontent.com/assets/14098140/15947076/930a6610-2e4e-11e6-94ea-2e5d9826f895.png)

**Comment by dlebu** [comment] 2016-06-09 21:29
This reproduces on OSX as well, but only for the Android platform.

**Comment by albertinad** [comment] 2016-06-09 21:30
@dlebu @guillaumejenkins Can I take this issue? This should happen only on android, since this exec call is called on android only. Usually in the device, the developer will be ask to grant permissions to the sensor, but in this case, we can default always to true.

**Comment by dlebu** [comment] 2016-06-09 21:31
Sure!

**Comment by albertinad** [comment] 2016-06-14 02:15
Fixed in #75

**Closed by albertinad** 2016-06-14 02:15 UTC
Labels: bug
